services:
  drawiodb:
    image: moonplkr/drawiodb:latest
    container_name: drawiodb
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DRAWIO_EXPORTER_URL=http://drawio-exporter:5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - moon_golem_network
    depends_on:
      - drawio-exporter
    labels:
      - "traefik.enable=true"
      # Main domain - serves frontend and API
      - "traefik.http.routers.drawiodb.rule=Host(`drawiodb.online`)"
      - "traefik.http.routers.drawiodb.entrypoints=websecure"
      - "traefik.http.routers.drawiodb.tls=true"
      - "traefik.http.routers.drawiodb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drawiodb.service=drawiodb"
      # API subdomain - same backend
      - "traefik.http.routers.drawiodb-api.rule=Host(`api.drawiodb.online`)"
      - "traefik.http.routers.drawiodb-api.entrypoints=websecure"
      - "traefik.http.routers.drawiodb-api.tls=true"
      - "traefik.http.routers.drawiodb-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drawiodb-api.service=drawiodb"
      # Service definition
      - "traefik.http.services.drawiodb.loadbalancer.server.port=8080"

  drawio-exporter:
    image: tomkludy/drawio-renderer:latest
    container_name: drawio-exporter
    restart: unless-stopped
    networks:
      - moon_golem_network
    # No external ports - internal use only
    # Service exposes HTTP REST API on port 5000 internally
    labels:
      - "traefik.enable=false"

networks:
  moon_golem_network:
    external: true